[project]
name = "pyblog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dependency-injector>=4.46.0",
    "fastapi[standard]>=0.115.12",
    "sqlalchemy>=2.0.40",
]
